export const LIST_THEATERS_REQUEST = "QuanLyRapReducer/LIST_THEATERS_REQUEST";
export const LIST_THEATERS_SUCCESS = "QuanLyRapReducer/LIST_THEATERS_SUCCESS";
export const LIST_THEATERS_FAILED = "QuanLyRapReducer/LIST_THEATERS_FAILED";

export const DETAIL_THEATER_REQUEST = "QuanLyRapReducer/DETAIL_THEATER_REQUEST";
export const DETAIL_THEATER_SUCCESS = "QuanLyRapReducer/DETAIL_THEATER_SUCCESS";
export const DETAIL_THEATER_FAILED = "QuanLyRapReducer/DETAIL_THEATER_FAILED";
export const MA_HE_THONG_RAP = "QuanLyRapReducer/MA_HE_THONG_RAP";
